vim.keymap.set('n','<C-T>',':tabnew<CR>')
vim.keymap.set('n','<C-S>',':w!<CR>')
vim.keymap.set('n','<C-I>',':tabnext<CR>')
vim.keymap.set('n','<C-L>',':tabclose<CR>')
vim.keymap.set('n','<leader>q',vim.cmd.Ex)
